# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flower_recognition' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flower_recognition
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON'
  pod 'SDWebImage'

end
